[package]
name = "vectorial"
version = "0.3.1"
authors = ["Martin Mills <daggerbot@gmail.com>"]
edition = "2021"
description = "Library for general-purpose vector math"
documentation = "https://docs.rs/vectorial"
repository = "https://github.com/daggerbot/vectorial"
license = "MPL-2.0"
